# coding: utf-8

"""
    virusapi

    The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_virus_api_client
from cloudmersive_virus_api_client.models.cloud_storage_virus_found import CloudStorageVirusFound  # noqa: E501
from cloudmersive_virus_api_client.rest import ApiException


class TestCloudStorageVirusFound(unittest.TestCase):
    """CloudStorageVirusFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCloudStorageVirusFound(self):
        """Test CloudStorageVirusFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_virus_api_client.models.cloud_storage_virus_found.CloudStorageVirusFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
