# coding: utf-8

"""
    virusapi

    Virus API lets you scan files and content for viruses and identify security issues with content.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_virus_api_client
from cloudmersive_virus_api_client.models.virus_found import VirusFound  # noqa: E501
from cloudmersive_virus_api_client.rest import ApiException


class TestVirusFound(unittest.TestCase):
    """VirusFound unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testVirusFound(self):
        """Test VirusFound"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_virus_api_client.models.virus_found.VirusFound()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
