# coding: utf-8

"""
    virusapi

    The Cloudmersive Virus Scan API lets you scan files and content for viruses and identify security issues with content.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import cloudmersive_virus_api_client
from cloudmersive_virus_api_client.models.additional_advanced_scan_information import AdditionalAdvancedScanInformation  # noqa: E501
from cloudmersive_virus_api_client.rest import ApiException


class TestAdditionalAdvancedScanInformation(unittest.TestCase):
    """AdditionalAdvancedScanInformation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdditionalAdvancedScanInformation(self):
        """Test AdditionalAdvancedScanInformation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = cloudmersive_virus_api_client.models.additional_advanced_scan_information.AdditionalAdvancedScanInformation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
