# coding: utf-8

# flake8: noqa

"""
    virusapi

    Virus API lets you scan files and content for viruses and identify security issues with content.  # noqa: E501

    OpenAPI spec version: v1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from cloudmersive_virus_api_client.api.scan_api import ScanApi

# import ApiClient
from cloudmersive_virus_api_client.api_client import ApiClient
from cloudmersive_virus_api_client.configuration import Configuration
# import models into sdk package
from cloudmersive_virus_api_client.models.virus_found import VirusFound
from cloudmersive_virus_api_client.models.virus_scan_result import VirusScanResult
